public namespace filetest2;
import core::common -;
import core::io -;
import core::io::errno -;

function void ft1(string const& fn)
{
  println("ft1");
  core::io::file::statbuf stbuf;
  core::io::file::io_stat(core::io::thread_io(), fn, stbuf);
  if (core::io::thread_io().get_errno() != EOK) {
    print("failed to stat: ");
    println(fn);
    print("error = ");
    println(core::io::thread_io().get_errno());
  } else {
    println(stbuf.st_size);
  }
}

function void ft2(string const& fn)
{
  println("ft2");
  const s = core::io::file::io_read_file(core::io::thread_io(), fn);
  print(*s.value);
}

set_stack_trace_limit(0);
try {
  ft1("hoge.txt");
  ft2("hoge.txt");
  ft1("hoge2.txt");
  ft2("hoge2.txt");
} catch (c_exception ex) {
  println("caught", ex);
}
