public namespace r1;
import common -;

{
  exception::set_stack_trace_limit(0);
  try {
    mutable vec = make_varray{int}(1, 2, 3, 4, 5, 6);
    cslice{int} sli = vec;
    const vv = make_varray{cslice{int}}(sli);
    println(vv);
    vec.resize(1000, 0); /* would invalidate */
    println(vv);
  } catch (c_exception ex) {
    println("caught", ex);
  }
}
